<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NOICLT66" name="Resit Capstone and CBT" tests="2" failures="1" timestamp="5 Jan 2016 05:48:53 GMT" time="126.087" errors="0">
  <testcase name="resitcapstoneBooking" time="67.691" classname="com.excelsoft.testautomation.TC_ABMS_ResitCapstoneBooking"/>
  <testcase name="resitCBTbooking" time="55.21" classname="com.excelsoft.testautomation.TC_ABMS_ResitCBTbooking">
    <failure type="java.lang.AssertionError" message="expected [Booking is created/updated successfully] but found [Something went wrong please try after some time.]">
      <![CDATA[java.lang.AssertionError: expected [Booking is created/updated successfully] but found [Something went wrong please try after some time.]
	at com.excelsoft.testautomation.TC_ABMS_ResitCBTbooking.resitCBTbooking(TC_ABMS_ResitCBTbooking.java:114)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- resitCBTbooking -->
</testsuite> <!-- Resit Capstone and CBT -->
